npm install -D @ckeditor/ckeditor5-adapter-ckfinder
npm install -D @ckeditor/ckeditor5-autoformat
npm install -D @ckeditor/ckeditor5-basic-styles
npm install -D @ckeditor/ckeditor5-block-quote
npm install -D @ckeditor/ckeditor5-ckfinder
npm install -D @ckeditor/ckeditor5-core
npm install -D @ckeditor/ckeditor5-dev-utils
npm install -D @ckeditor/ckeditor5-dev-webpack-plugin
npm install -D @ckeditor/ckeditor5-easy-image
npm install -D @ckeditor/ckeditor5-editor-classic
npm install -D @ckeditor/ckeditor5-essentials
npm install -D @ckeditor/ckeditor5-heading
npm install -D @ckeditor/ckeditor5-image
npm install -D @ckeditor/ckeditor5-indent
npm install -D @ckeditor/ckeditor5-link
npm install -D @ckeditor/ckeditor5-list
npm install -D @ckeditor/ckeditor5-media-embed
npm install -D @ckeditor/ckeditor5-paragraph
npm install -D @ckeditor/ckeditor5-paste-from-office
npm install -D @ckeditor/ckeditor5-table
npm install -D @ckeditor/ckeditor5-typing
npm install -D @ckeditor/ckeditor5-theme-lark